/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes-admin/__root'
import { Route as RegistroRouteImport } from './routes-admin/registro'
import { Route as NoAccessRouteImport } from './routes-admin/no-access'
import { Route as LoginRouteImport } from './routes-admin/login'
import { Route as AuthenticatedRouteImport } from './routes-admin/_authenticated'
import { Route as IndexRouteImport } from './routes-admin/index'
import { Route as AuthenticatedSelectAccountRouteImport } from './routes-admin/_authenticated/select-account'
import { Route as AuthenticatedAccessPausedRouteImport } from './routes-admin/_authenticated/access-paused'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes-admin/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes-admin/_authenticated/admin/index'
import { Route as InvitationsStaffTokenRouteImport } from './routes-admin/invitations/staff.$token'
import { Route as AuthenticatedAdminVisitorsRouteImport } from './routes-admin/_authenticated/admin/visitors'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes-admin/_authenticated/admin/units'
import { Route as AuthenticatedAdminSubscriptionRouteImport } from './routes-admin/_authenticated/admin/subscription'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes-admin/_authenticated/admin/staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes-admin/_authenticated/admin/settings'
import { Route as AuthenticatedAdminResidentsRouteImport } from './routes-admin/_authenticated/admin/residents'
import { Route as AuthenticatedAdminReservationsRouteImport } from './routes-admin/_authenticated/admin/reservations'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes-admin/_authenticated/admin/packages'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes-admin/_authenticated/admin/locations'
import { Route as AuthenticatedAdminFinancesRouteImport } from './routes-admin/_authenticated/admin/finances'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes-admin/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes-admin/_authenticated/admin/activity'
import { Route as AuthenticatedAdminAccountRouteImport } from './routes-admin/_authenticated/admin/account'
import { Route as AuthenticatedAdminUnitsUnitIdRouteImport } from './routes-admin/_authenticated/admin/units_.$unitId'
import { Route as AuthenticatedAdminRegistryVehiclesRouteImport } from './routes-admin/_authenticated/admin/registry/vehicles'
import { Route as AuthenticatedAdminRegistryUnitsRouteImport } from './routes-admin/_authenticated/admin/registry/units'
import { Route as AuthenticatedAdminRegistryResidentsRouteImport } from './routes-admin/_authenticated/admin/registry/residents'
import { Route as AuthenticatedAdminLocationsLocationIdRouteImport } from './routes-admin/_authenticated/admin/locations_.$locationId'
import { Route as AuthenticatedAdminRegistryUnitsUnitIdRouteImport } from './routes-admin/_authenticated/admin/registry/units_.$unitId'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSelectAccountRoute =
  AuthenticatedSelectAccountRouteImport.update({
    id: '/select-account',
    path: '/select-account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccessPausedRoute =
  AuthenticatedAccessPausedRouteImport.update({
    id: '/access-paused',
    path: '/access-paused',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const InvitationsStaffTokenRoute = InvitationsStaffTokenRouteImport.update({
  id: '/invitations/staff/$token',
  path: '/invitations/staff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVisitorsRoute =
  AuthenticatedAdminVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSubscriptionRoute =
  AuthenticatedAdminSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResidentsRoute =
  AuthenticatedAdminResidentsRouteImport.update({
    id: '/residents',
    path: '/residents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReservationsRoute =
  AuthenticatedAdminReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancesRoute =
  AuthenticatedAdminFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountRoute =
  AuthenticatedAdminAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnitsUnitIdRoute =
  AuthenticatedAdminUnitsUnitIdRouteImport.update({
    id: '/units_/$unitId',
    path: '/units/$unitId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryVehiclesRoute =
  AuthenticatedAdminRegistryVehiclesRouteImport.update({
    id: '/registry/vehicles',
    path: '/registry/vehicles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryUnitsRoute =
  AuthenticatedAdminRegistryUnitsRouteImport.update({
    id: '/registry/units',
    path: '/registry/units',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryResidentsRoute =
  AuthenticatedAdminRegistryResidentsRouteImport.update({
    id: '/registry/residents',
    path: '/registry/residents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLocationsLocationIdRoute =
  AuthenticatedAdminLocationsLocationIdRouteImport.update({
    id: '/locations_/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryUnitsUnitIdRoute =
  AuthenticatedAdminRegistryUnitsUnitIdRouteImport.update({
    id: '/registry/units_/$unitId',
    path: '/registry/units/$unitId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/registro': typeof RegistroRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/access-paused': typeof AuthenticatedAccessPausedRoute
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/subscription': typeof AuthenticatedAdminSubscriptionRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/invitations/staff/$token': typeof InvitationsStaffTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/locations/$locationId': typeof AuthenticatedAdminLocationsLocationIdRoute
  '/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
  '/admin/units/$unitId': typeof AuthenticatedAdminUnitsUnitIdRoute
  '/admin/registry/units/$unitId': typeof AuthenticatedAdminRegistryUnitsUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/registro': typeof RegistroRoute
  '/access-paused': typeof AuthenticatedAccessPausedRoute
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/subscription': typeof AuthenticatedAdminSubscriptionRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/invitations/staff/$token': typeof InvitationsStaffTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/locations/$locationId': typeof AuthenticatedAdminLocationsLocationIdRoute
  '/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
  '/admin/units/$unitId': typeof AuthenticatedAdminUnitsUnitIdRoute
  '/admin/registry/units/$unitId': typeof AuthenticatedAdminRegistryUnitsUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/registro': typeof RegistroRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/access-paused': typeof AuthenticatedAccessPausedRoute
  '/_authenticated/select-account': typeof AuthenticatedSelectAccountRoute
  '/_authenticated/admin/account': typeof AuthenticatedAdminAccountRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/_authenticated/admin/residents': typeof AuthenticatedAdminResidentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/subscription': typeof AuthenticatedAdminSubscriptionRoute
  '/_authenticated/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/_authenticated/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/invitations/staff/$token': typeof InvitationsStaffTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/locations_/$locationId': typeof AuthenticatedAdminLocationsLocationIdRoute
  '/_authenticated/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/_authenticated/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/_authenticated/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
  '/_authenticated/admin/units_/$unitId': typeof AuthenticatedAdminUnitsUnitIdRoute
  '/_authenticated/admin/registry/units_/$unitId': typeof AuthenticatedAdminRegistryUnitsUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-access'
    | '/registro'
    | '/admin'
    | '/access-paused'
    | '/select-account'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/finances'
    | '/admin/locations'
    | '/admin/packages'
    | '/admin/reservations'
    | '/admin/residents'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscription'
    | '/admin/units'
    | '/admin/visitors'
    | '/invitations/staff/$token'
    | '/admin/'
    | '/admin/locations/$locationId'
    | '/admin/registry/residents'
    | '/admin/registry/units'
    | '/admin/registry/vehicles'
    | '/admin/units/$unitId'
    | '/admin/registry/units/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/registro'
    | '/access-paused'
    | '/select-account'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/finances'
    | '/admin/locations'
    | '/admin/packages'
    | '/admin/reservations'
    | '/admin/residents'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscription'
    | '/admin/units'
    | '/admin/visitors'
    | '/invitations/staff/$token'
    | '/admin'
    | '/admin/locations/$locationId'
    | '/admin/registry/residents'
    | '/admin/registry/units'
    | '/admin/registry/vehicles'
    | '/admin/units/$unitId'
    | '/admin/registry/units/$unitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/no-access'
    | '/registro'
    | '/_authenticated/admin'
    | '/_authenticated/access-paused'
    | '/_authenticated/select-account'
    | '/_authenticated/admin/account'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/finances'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/reservations'
    | '/_authenticated/admin/residents'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/subscription'
    | '/_authenticated/admin/units'
    | '/_authenticated/admin/visitors'
    | '/invitations/staff/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/locations_/$locationId'
    | '/_authenticated/admin/registry/residents'
    | '/_authenticated/admin/registry/units'
    | '/_authenticated/admin/registry/vehicles'
    | '/_authenticated/admin/units_/$unitId'
    | '/_authenticated/admin/registry/units_/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  RegistroRoute: typeof RegistroRoute
  InvitationsStaffTokenRoute: typeof InvitationsStaffTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/select-account': {
      id: '/_authenticated/select-account'
      path: '/select-account'
      fullPath: '/select-account'
      preLoaderRoute: typeof AuthenticatedSelectAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access-paused': {
      id: '/_authenticated/access-paused'
      path: '/access-paused'
      fullPath: '/access-paused'
      preLoaderRoute: typeof AuthenticatedAccessPausedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/invitations/staff/$token': {
      id: '/invitations/staff/$token'
      path: '/invitations/staff/$token'
      fullPath: '/invitations/staff/$token'
      preLoaderRoute: typeof InvitationsStaffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/visitors': {
      id: '/_authenticated/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AuthenticatedAdminVisitorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units': {
      id: '/_authenticated/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscription': {
      id: '/_authenticated/admin/subscription'
      path: '/subscription'
      fullPath: '/admin/subscription'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/residents': {
      id: '/_authenticated/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AuthenticatedAdminResidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reservations': {
      id: '/_authenticated/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AuthenticatedAdminReservationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finances': {
      id: '/_authenticated/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AuthenticatedAdminFinancesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/account': {
      id: '/_authenticated/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AuthenticatedAdminAccountRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/units_/$unitId': {
      id: '/_authenticated/admin/units_/$unitId'
      path: '/units/$unitId'
      fullPath: '/admin/units/$unitId'
      preLoaderRoute: typeof AuthenticatedAdminUnitsUnitIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/vehicles': {
      id: '/_authenticated/admin/registry/vehicles'
      path: '/registry/vehicles'
      fullPath: '/admin/registry/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminRegistryVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/units': {
      id: '/_authenticated/admin/registry/units'
      path: '/registry/units'
      fullPath: '/admin/registry/units'
      preLoaderRoute: typeof AuthenticatedAdminRegistryUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/residents': {
      id: '/_authenticated/admin/registry/residents'
      path: '/registry/residents'
      fullPath: '/admin/registry/residents'
      preLoaderRoute: typeof AuthenticatedAdminRegistryResidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/locations_/$locationId': {
      id: '/_authenticated/admin/locations_/$locationId'
      path: '/locations/$locationId'
      fullPath: '/admin/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedAdminLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/units_/$unitId': {
      id: '/_authenticated/admin/registry/units_/$unitId'
      path: '/registry/units/$unitId'
      fullPath: '/admin/registry/units/$unitId'
      preLoaderRoute: typeof AuthenticatedAdminRegistryUnitsUnitIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccountRoute: typeof AuthenticatedAdminAccountRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminFinancesRoute: typeof AuthenticatedAdminFinancesRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminReservationsRoute: typeof AuthenticatedAdminReservationsRoute
  AuthenticatedAdminResidentsRoute: typeof AuthenticatedAdminResidentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminSubscriptionRoute: typeof AuthenticatedAdminSubscriptionRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRoute
  AuthenticatedAdminVisitorsRoute: typeof AuthenticatedAdminVisitorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLocationsLocationIdRoute: typeof AuthenticatedAdminLocationsLocationIdRoute
  AuthenticatedAdminRegistryResidentsRoute: typeof AuthenticatedAdminRegistryResidentsRoute
  AuthenticatedAdminRegistryUnitsRoute: typeof AuthenticatedAdminRegistryUnitsRoute
  AuthenticatedAdminRegistryVehiclesRoute: typeof AuthenticatedAdminRegistryVehiclesRoute
  AuthenticatedAdminUnitsUnitIdRoute: typeof AuthenticatedAdminUnitsUnitIdRoute
  AuthenticatedAdminRegistryUnitsUnitIdRoute: typeof AuthenticatedAdminRegistryUnitsUnitIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccountRoute: AuthenticatedAdminAccountRoute,
    AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminFinancesRoute: AuthenticatedAdminFinancesRoute,
    AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
    AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
    AuthenticatedAdminReservationsRoute: AuthenticatedAdminReservationsRoute,
    AuthenticatedAdminResidentsRoute: AuthenticatedAdminResidentsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminSubscriptionRoute: AuthenticatedAdminSubscriptionRoute,
    AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRoute,
    AuthenticatedAdminVisitorsRoute: AuthenticatedAdminVisitorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminLocationsLocationIdRoute:
      AuthenticatedAdminLocationsLocationIdRoute,
    AuthenticatedAdminRegistryResidentsRoute:
      AuthenticatedAdminRegistryResidentsRoute,
    AuthenticatedAdminRegistryUnitsRoute: AuthenticatedAdminRegistryUnitsRoute,
    AuthenticatedAdminRegistryVehiclesRoute:
      AuthenticatedAdminRegistryVehiclesRoute,
    AuthenticatedAdminUnitsUnitIdRoute: AuthenticatedAdminUnitsUnitIdRoute,
    AuthenticatedAdminRegistryUnitsUnitIdRoute:
      AuthenticatedAdminRegistryUnitsUnitIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccessPausedRoute: typeof AuthenticatedAccessPausedRoute
  AuthenticatedSelectAccountRoute: typeof AuthenticatedSelectAccountRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccessPausedRoute: AuthenticatedAccessPausedRoute,
  AuthenticatedSelectAccountRoute: AuthenticatedSelectAccountRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  RegistroRoute: RegistroRoute,
  InvitationsStaffTokenRoute: InvitationsStaffTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
