/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes-portal/__root'
import { Route as NoAccessRouteImport } from './routes-portal/no-access'
import { Route as LoginRouteImport } from './routes-portal/login'
import { Route as AuthenticatedRouteImport } from './routes-portal/_authenticated'
import { Route as IndexRouteImport } from './routes-portal/index'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes-portal/_authenticated/portal/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes-portal/_authenticated/portal/index'
import { Route as InvitationsResidentTokenRouteImport } from './routes-portal/invitations/resident.$token'
import { Route as AuthenticatedPortalVisitasRouteImport } from './routes-portal/_authenticated/portal/visitas'
import { Route as AuthenticatedPortalReservasRouteImport } from './routes-portal/_authenticated/portal/reservas'
import { Route as AuthenticatedPortalPerfilRouteImport } from './routes-portal/_authenticated/portal/perfil'
import { Route as AuthenticatedPortalVisitasNuevaRouteImport } from './routes-portal/_authenticated/portal/visitas_.nueva'
import { Route as AuthenticatedPortalReservasAmenidadesAmenityIdRouteImport } from './routes-portal/_authenticated/portal/reservas_.amenidades.$amenityId'
import { Route as AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRouteImport } from './routes-portal/_authenticated/portal/reservas_.amenidades.$amenityId_.horario'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const InvitationsResidentTokenRoute =
  InvitationsResidentTokenRouteImport.update({
    id: '/invitations/resident/$token',
    path: '/invitations/resident/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalVisitasRoute =
  AuthenticatedPortalVisitasRouteImport.update({
    id: '/visitas',
    path: '/visitas',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalReservasRoute =
  AuthenticatedPortalReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPerfilRoute =
  AuthenticatedPortalPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalVisitasNuevaRoute =
  AuthenticatedPortalVisitasNuevaRouteImport.update({
    id: '/visitas_/nueva',
    path: '/visitas/nueva',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalReservasAmenidadesAmenityIdRoute =
  AuthenticatedPortalReservasAmenidadesAmenityIdRouteImport.update({
    id: '/reservas_/amenidades/$amenityId',
    path: '/reservas/amenidades/$amenityId',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute =
  AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRouteImport.update({
    id: '/reservas_/amenidades/$amenityId_/horario',
    path: '/reservas/amenidades/$amenityId/horario',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/portal/perfil': typeof AuthenticatedPortalPerfilRoute
  '/portal/reservas': typeof AuthenticatedPortalReservasRoute
  '/portal/visitas': typeof AuthenticatedPortalVisitasRoute
  '/invitations/resident/$token': typeof InvitationsResidentTokenRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/visitas/nueva': typeof AuthenticatedPortalVisitasNuevaRoute
  '/portal/reservas/amenidades/$amenityId': typeof AuthenticatedPortalReservasAmenidadesAmenityIdRoute
  '/portal/reservas/amenidades/$amenityId/horario': typeof AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/portal/perfil': typeof AuthenticatedPortalPerfilRoute
  '/portal/reservas': typeof AuthenticatedPortalReservasRoute
  '/portal/visitas': typeof AuthenticatedPortalVisitasRoute
  '/invitations/resident/$token': typeof InvitationsResidentTokenRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/visitas/nueva': typeof AuthenticatedPortalVisitasNuevaRoute
  '/portal/reservas/amenidades/$amenityId': typeof AuthenticatedPortalReservasAmenidadesAmenityIdRoute
  '/portal/reservas/amenidades/$amenityId/horario': typeof AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/portal/perfil': typeof AuthenticatedPortalPerfilRoute
  '/_authenticated/portal/reservas': typeof AuthenticatedPortalReservasRoute
  '/_authenticated/portal/visitas': typeof AuthenticatedPortalVisitasRoute
  '/invitations/resident/$token': typeof InvitationsResidentTokenRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/visitas_/nueva': typeof AuthenticatedPortalVisitasNuevaRoute
  '/_authenticated/portal/reservas_/amenidades/$amenityId': typeof AuthenticatedPortalReservasAmenidadesAmenityIdRoute
  '/_authenticated/portal/reservas_/amenidades/$amenityId_/horario': typeof AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-access'
    | '/portal'
    | '/portal/perfil'
    | '/portal/reservas'
    | '/portal/visitas'
    | '/invitations/resident/$token'
    | '/portal/'
    | '/portal/visitas/nueva'
    | '/portal/reservas/amenidades/$amenityId'
    | '/portal/reservas/amenidades/$amenityId/horario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/portal/perfil'
    | '/portal/reservas'
    | '/portal/visitas'
    | '/invitations/resident/$token'
    | '/portal'
    | '/portal/visitas/nueva'
    | '/portal/reservas/amenidades/$amenityId'
    | '/portal/reservas/amenidades/$amenityId/horario'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/no-access'
    | '/_authenticated/portal'
    | '/_authenticated/portal/perfil'
    | '/_authenticated/portal/reservas'
    | '/_authenticated/portal/visitas'
    | '/invitations/resident/$token'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/visitas_/nueva'
    | '/_authenticated/portal/reservas_/amenidades/$amenityId'
    | '/_authenticated/portal/reservas_/amenidades/$amenityId_/horario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  InvitationsResidentTokenRoute: typeof InvitationsResidentTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/invitations/resident/$token': {
      id: '/invitations/resident/$token'
      path: '/invitations/resident/$token'
      fullPath: '/invitations/resident/$token'
      preLoaderRoute: typeof InvitationsResidentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/visitas': {
      id: '/_authenticated/portal/visitas'
      path: '/visitas'
      fullPath: '/portal/visitas'
      preLoaderRoute: typeof AuthenticatedPortalVisitasRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/reservas': {
      id: '/_authenticated/portal/reservas'
      path: '/reservas'
      fullPath: '/portal/reservas'
      preLoaderRoute: typeof AuthenticatedPortalReservasRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/perfil': {
      id: '/_authenticated/portal/perfil'
      path: '/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof AuthenticatedPortalPerfilRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/visitas_/nueva': {
      id: '/_authenticated/portal/visitas_/nueva'
      path: '/visitas/nueva'
      fullPath: '/portal/visitas/nueva'
      preLoaderRoute: typeof AuthenticatedPortalVisitasNuevaRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/reservas_/amenidades/$amenityId': {
      id: '/_authenticated/portal/reservas_/amenidades/$amenityId'
      path: '/reservas/amenidades/$amenityId'
      fullPath: '/portal/reservas/amenidades/$amenityId'
      preLoaderRoute: typeof AuthenticatedPortalReservasAmenidadesAmenityIdRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/reservas_/amenidades/$amenityId_/horario': {
      id: '/_authenticated/portal/reservas_/amenidades/$amenityId_/horario'
      path: '/reservas/amenidades/$amenityId/horario'
      fullPath: '/portal/reservas/amenidades/$amenityId/horario'
      preLoaderRoute: typeof AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
  }
}

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalPerfilRoute: typeof AuthenticatedPortalPerfilRoute
  AuthenticatedPortalReservasRoute: typeof AuthenticatedPortalReservasRoute
  AuthenticatedPortalVisitasRoute: typeof AuthenticatedPortalVisitasRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalVisitasNuevaRoute: typeof AuthenticatedPortalVisitasNuevaRoute
  AuthenticatedPortalReservasAmenidadesAmenityIdRoute: typeof AuthenticatedPortalReservasAmenidadesAmenityIdRoute
  AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute: typeof AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalPerfilRoute: AuthenticatedPortalPerfilRoute,
    AuthenticatedPortalReservasRoute: AuthenticatedPortalReservasRoute,
    AuthenticatedPortalVisitasRoute: AuthenticatedPortalVisitasRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
    AuthenticatedPortalVisitasNuevaRoute: AuthenticatedPortalVisitasNuevaRoute,
    AuthenticatedPortalReservasAmenidadesAmenityIdRoute:
      AuthenticatedPortalReservasAmenidadesAmenityIdRoute,
    AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute:
      AuthenticatedPortalReservasAmenidadesAmenityIdHorarioRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  InvitationsResidentTokenRoute: InvitationsResidentTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
