/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSelectAccountRouteImport } from './routes/_authenticated/select-account'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedFrontDeskRouteRouteImport } from './routes/_authenticated/front-desk/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as InvitationsStaffTokenRouteImport } from './routes/invitations/staff.$token'
import { Route as InvitationsResidentTokenRouteImport } from './routes/invitations/resident.$token'
import { Route as AuthenticatedAdminVisitorsRouteImport } from './routes/_authenticated/admin/visitors'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReservationsRouteImport } from './routes/_authenticated/admin/reservations'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/admin/locations'
import { Route as AuthenticatedAdminFinancesRouteImport } from './routes/_authenticated/admin/finances'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin/activity'
import { Route as AuthenticatedAdminRegistryVehiclesRouteImport } from './routes/_authenticated/admin/registry/vehicles'
import { Route as AuthenticatedAdminRegistryUnitsRouteImport } from './routes/_authenticated/admin/registry/units'
import { Route as AuthenticatedAdminRegistryResidentsRouteImport } from './routes/_authenticated/admin/registry/residents'
import { Route as AuthenticatedAdminRegistryImportsRouteImport } from './routes/_authenticated/admin/registry/imports'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSelectAccountRoute =
  AuthenticatedSelectAccountRouteImport.update({
    id: '/select-account',
    path: '/select-account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFrontDeskRouteRoute =
  AuthenticatedFrontDeskRouteRouteImport.update({
    id: '/front-desk',
    path: '/front-desk',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const InvitationsStaffTokenRoute = InvitationsStaffTokenRouteImport.update({
  id: '/invitations/staff/$token',
  path: '/invitations/staff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsResidentTokenRoute =
  InvitationsResidentTokenRouteImport.update({
    id: '/invitations/resident/$token',
    path: '/invitations/resident/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminVisitorsRoute =
  AuthenticatedAdminVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReservationsRoute =
  AuthenticatedAdminReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancesRoute =
  AuthenticatedAdminFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryVehiclesRoute =
  AuthenticatedAdminRegistryVehiclesRouteImport.update({
    id: '/registry/vehicles',
    path: '/registry/vehicles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryUnitsRoute =
  AuthenticatedAdminRegistryUnitsRouteImport.update({
    id: '/registry/units',
    path: '/registry/units',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryResidentsRoute =
  AuthenticatedAdminRegistryResidentsRouteImport.update({
    id: '/registry/residents',
    path: '/registry/residents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryImportsRoute =
  AuthenticatedAdminRegistryImportsRouteImport.update({
    id: '/registry/imports',
    path: '/registry/imports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/front-desk': typeof AuthenticatedFrontDeskRouteRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/invitations/resident/$token': typeof InvitationsResidentTokenRoute
  '/invitations/staff/$token': typeof InvitationsStaffTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/registry/imports': typeof AuthenticatedAdminRegistryImportsRoute
  '/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/front-desk': typeof AuthenticatedFrontDeskRouteRoute
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/invitations/resident/$token': typeof InvitationsResidentTokenRoute
  '/invitations/staff/$token': typeof InvitationsStaffTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/registry/imports': typeof AuthenticatedAdminRegistryImportsRoute
  '/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/front-desk': typeof AuthenticatedFrontDeskRouteRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/select-account': typeof AuthenticatedSelectAccountRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/invitations/resident/$token': typeof InvitationsResidentTokenRoute
  '/invitations/staff/$token': typeof InvitationsStaffTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/registry/imports': typeof AuthenticatedAdminRegistryImportsRoute
  '/_authenticated/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/_authenticated/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/_authenticated/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-access'
    | '/admin'
    | '/front-desk'
    | '/portal'
    | '/select-account'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/finances'
    | '/admin/locations'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/visitors'
    | '/invitations/resident/$token'
    | '/invitations/staff/$token'
    | '/admin/'
    | '/portal/'
    | '/admin/registry/imports'
    | '/admin/registry/residents'
    | '/admin/registry/units'
    | '/admin/registry/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/front-desk'
    | '/select-account'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/finances'
    | '/admin/locations'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/visitors'
    | '/invitations/resident/$token'
    | '/invitations/staff/$token'
    | '/admin'
    | '/portal'
    | '/admin/registry/imports'
    | '/admin/registry/residents'
    | '/admin/registry/units'
    | '/admin/registry/vehicles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/no-access'
    | '/_authenticated/admin'
    | '/_authenticated/front-desk'
    | '/_authenticated/portal'
    | '/_authenticated/select-account'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/finances'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/reservations'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/visitors'
    | '/invitations/resident/$token'
    | '/invitations/staff/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/registry/imports'
    | '/_authenticated/admin/registry/residents'
    | '/_authenticated/admin/registry/units'
    | '/_authenticated/admin/registry/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  InvitationsResidentTokenRoute: typeof InvitationsResidentTokenRoute
  InvitationsStaffTokenRoute: typeof InvitationsStaffTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/select-account': {
      id: '/_authenticated/select-account'
      path: '/select-account'
      fullPath: '/select-account'
      preLoaderRoute: typeof AuthenticatedSelectAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/front-desk': {
      id: '/_authenticated/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof AuthenticatedFrontDeskRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/invitations/staff/$token': {
      id: '/invitations/staff/$token'
      path: '/invitations/staff/$token'
      fullPath: '/invitations/staff/$token'
      preLoaderRoute: typeof InvitationsStaffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/resident/$token': {
      id: '/invitations/resident/$token'
      path: '/invitations/resident/$token'
      fullPath: '/invitations/resident/$token'
      preLoaderRoute: typeof InvitationsResidentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/visitors': {
      id: '/_authenticated/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AuthenticatedAdminVisitorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reservations': {
      id: '/_authenticated/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AuthenticatedAdminReservationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finances': {
      id: '/_authenticated/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AuthenticatedAdminFinancesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/vehicles': {
      id: '/_authenticated/admin/registry/vehicles'
      path: '/registry/vehicles'
      fullPath: '/admin/registry/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminRegistryVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/units': {
      id: '/_authenticated/admin/registry/units'
      path: '/registry/units'
      fullPath: '/admin/registry/units'
      preLoaderRoute: typeof AuthenticatedAdminRegistryUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/residents': {
      id: '/_authenticated/admin/registry/residents'
      path: '/registry/residents'
      fullPath: '/admin/registry/residents'
      preLoaderRoute: typeof AuthenticatedAdminRegistryResidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/imports': {
      id: '/_authenticated/admin/registry/imports'
      path: '/registry/imports'
      fullPath: '/admin/registry/imports'
      preLoaderRoute: typeof AuthenticatedAdminRegistryImportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminFinancesRoute: typeof AuthenticatedAdminFinancesRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminReservationsRoute: typeof AuthenticatedAdminReservationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminVisitorsRoute: typeof AuthenticatedAdminVisitorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRegistryImportsRoute: typeof AuthenticatedAdminRegistryImportsRoute
  AuthenticatedAdminRegistryResidentsRoute: typeof AuthenticatedAdminRegistryResidentsRoute
  AuthenticatedAdminRegistryUnitsRoute: typeof AuthenticatedAdminRegistryUnitsRoute
  AuthenticatedAdminRegistryVehiclesRoute: typeof AuthenticatedAdminRegistryVehiclesRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminFinancesRoute: AuthenticatedAdminFinancesRoute,
    AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
    AuthenticatedAdminReservationsRoute: AuthenticatedAdminReservationsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminVisitorsRoute: AuthenticatedAdminVisitorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminRegistryImportsRoute:
      AuthenticatedAdminRegistryImportsRoute,
    AuthenticatedAdminRegistryResidentsRoute:
      AuthenticatedAdminRegistryResidentsRoute,
    AuthenticatedAdminRegistryUnitsRoute: AuthenticatedAdminRegistryUnitsRoute,
    AuthenticatedAdminRegistryVehiclesRoute:
      AuthenticatedAdminRegistryVehiclesRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFrontDeskRouteRoute: typeof AuthenticatedFrontDeskRouteRoute
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
  AuthenticatedSelectAccountRoute: typeof AuthenticatedSelectAccountRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFrontDeskRouteRoute: AuthenticatedFrontDeskRouteRoute,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
  AuthenticatedSelectAccountRoute: AuthenticatedSelectAccountRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  InvitationsResidentTokenRoute: InvitationsResidentTokenRoute,
  InvitationsStaffTokenRoute: InvitationsStaffTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
