/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSelectAccountRouteImport } from './routes/_authenticated/select-account'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedFrontDeskRouteRouteImport } from './routes/_authenticated/front-desk/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminRegistryVehiclesRouteImport } from './routes/_authenticated/admin/registry/vehicles'
import { Route as AuthenticatedAdminRegistryUnitsRouteImport } from './routes/_authenticated/admin/registry/units'
import { Route as AuthenticatedAdminRegistryResidentsRouteImport } from './routes/_authenticated/admin/registry/residents'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSelectAccountRoute =
  AuthenticatedSelectAccountRouteImport.update({
    id: '/select-account',
    path: '/select-account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFrontDeskRouteRoute =
  AuthenticatedFrontDeskRouteRouteImport.update({
    id: '/front-desk',
    path: '/front-desk',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminRegistryVehiclesRoute =
  AuthenticatedAdminRegistryVehiclesRouteImport.update({
    id: '/registry/vehicles',
    path: '/registry/vehicles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryUnitsRoute =
  AuthenticatedAdminRegistryUnitsRouteImport.update({
    id: '/registry/units',
    path: '/registry/units',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistryResidentsRoute =
  AuthenticatedAdminRegistryResidentsRouteImport.update({
    id: '/registry/residents',
    path: '/registry/residents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/front-desk': typeof AuthenticatedFrontDeskRouteRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/front-desk': typeof AuthenticatedFrontDeskRouteRoute
  '/select-account': typeof AuthenticatedSelectAccountRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/front-desk': typeof AuthenticatedFrontDeskRouteRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/select-account': typeof AuthenticatedSelectAccountRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/registry/residents': typeof AuthenticatedAdminRegistryResidentsRoute
  '/_authenticated/admin/registry/units': typeof AuthenticatedAdminRegistryUnitsRoute
  '/_authenticated/admin/registry/vehicles': typeof AuthenticatedAdminRegistryVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-access'
    | '/admin'
    | '/front-desk'
    | '/portal'
    | '/select-account'
    | '/admin/'
    | '/portal/'
    | '/admin/registry/residents'
    | '/admin/registry/units'
    | '/admin/registry/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/front-desk'
    | '/select-account'
    | '/admin'
    | '/portal'
    | '/admin/registry/residents'
    | '/admin/registry/units'
    | '/admin/registry/vehicles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/no-access'
    | '/_authenticated/admin'
    | '/_authenticated/front-desk'
    | '/_authenticated/portal'
    | '/_authenticated/select-account'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/registry/residents'
    | '/_authenticated/admin/registry/units'
    | '/_authenticated/admin/registry/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/select-account': {
      id: '/_authenticated/select-account'
      path: '/select-account'
      fullPath: '/select-account'
      preLoaderRoute: typeof AuthenticatedSelectAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/front-desk': {
      id: '/_authenticated/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof AuthenticatedFrontDeskRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/vehicles': {
      id: '/_authenticated/admin/registry/vehicles'
      path: '/registry/vehicles'
      fullPath: '/admin/registry/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminRegistryVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/units': {
      id: '/_authenticated/admin/registry/units'
      path: '/registry/units'
      fullPath: '/admin/registry/units'
      preLoaderRoute: typeof AuthenticatedAdminRegistryUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registry/residents': {
      id: '/_authenticated/admin/registry/residents'
      path: '/registry/residents'
      fullPath: '/admin/registry/residents'
      preLoaderRoute: typeof AuthenticatedAdminRegistryResidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRegistryResidentsRoute: typeof AuthenticatedAdminRegistryResidentsRoute
  AuthenticatedAdminRegistryUnitsRoute: typeof AuthenticatedAdminRegistryUnitsRoute
  AuthenticatedAdminRegistryVehiclesRoute: typeof AuthenticatedAdminRegistryVehiclesRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminRegistryResidentsRoute:
      AuthenticatedAdminRegistryResidentsRoute,
    AuthenticatedAdminRegistryUnitsRoute: AuthenticatedAdminRegistryUnitsRoute,
    AuthenticatedAdminRegistryVehiclesRoute:
      AuthenticatedAdminRegistryVehiclesRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFrontDeskRouteRoute: typeof AuthenticatedFrontDeskRouteRoute
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
  AuthenticatedSelectAccountRoute: typeof AuthenticatedSelectAccountRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFrontDeskRouteRoute: AuthenticatedFrontDeskRouteRoute,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
  AuthenticatedSelectAccountRoute: AuthenticatedSelectAccountRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
